### ISSUE TITLE
Aimbot aims above the characters head.

### ISSUE THREAD

**Issue by WhyNotHentai** [Jire/Overwatcheat#100]
Have just managed to install the cheat and i've noticed the aimbot always aims above the player models head. I honestly have no idea whats wrong.

Here's the video:
https://youtu.be/dEKO-PIdlHY

Here's my config:
https://pastebin.com/LnT3PYRs

**Comment by xtherk** [comment]
If you want to aim at the body, you can increase the value of `aim_offset_y`.  e.g `aim_offset_y = 1.0`

**Comment by WhyNotHentai** [comment]
> 
> 
> If you want to aim at the body, you can increase the value of `aim_offset_y`. e.g `aim_offset_y = 1.0`

Thank you so much I increased it and its finally aiming where its supposed to.
