### ISSUE TITLE
incorrect aim box fhd1080 

### ISSUE THREAD

**Issue by Asofwar** [Jire/Overwatcheat#104]
if 2 enemy stay around , aim centering of they
2box in 1box )

**Comment by xtherk** [comment]
please refer to this answer https://github.com/Jire/Overwatcheat/issues/94#issuecomment-864377892

**Comment by Asofwar** [comment]
> please refer to this answer [#94 (comment)](https://github.com/Jire/Overwatcheat/issues/94#issuecomment-864377892)

thanks!
