### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by Petee464** [Jire/Overwatcheat#105]
* What went wrong:
Could not compile settings file 'C:\Users\XY\Desktop\Overwatcheat-3.5.0\settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 61

what could be the problem?

**Comment by JuliTra** [comment]
I have the same issue, did you find a solution?

**Comment by DoctorAnon** [comment]
I have the same issue
