### ISSUE TITLE
Read me if your aimbot is not working

### ISSUE THREAD

**Issue by xtherk** [Jire/Overwatcheat#153]
I summed up some problems you can check.

If your Aimbot is not working:

1. Check if the InterceptionDrive is installed and reboot.

2. Check if magenta is set for enemies in game.
> Game Options -> Color Blind -> Enemy Color Change -> Magenta

3. If you use the version of Overwatcheat I released, it's recommended to use full screen with `window_title_search=desktop`, using windowed may capture a black screen and cause aimbot to not work.

Please check each step carefully, if the above steps are completed, the aimbot is likely to work.

**Comment by xtherk** [comment]
If your aimbot works fine but you feel the configuration is not good enough, for example what configuration should the widow maker use.

I don't have so much time to adjust the parameters for you, please carefully follow the description of each parameter in overwatcheat.cfg and make changes slowly until you are satisfied.

But I can give some suggestions as follows: 

1. You can try to reduce the `sensitivity` of the bot, the smaller the sensitivity value, the faster the tracking (flick) speed. 
> Allows you to move the crosshair to the target faster

2. Reduce sleep time
> Let aimbot identify targets faster

3. [flick mode] Lower the value of flick_pause_duration, between 20-100

These can improve the hit rate.

Please adjust other parameters according to the configuration description.

**Comment by yege16888** [comment]
window_title_search=XXXXX  
XXXXX needs to be changed to the title of your game window. The game window title may also be different for different languages.

**Comment by xtherk** [comment]
> window_title_search=XXXXX XXXXX needs to be changed to the title of your game window. The game window title may also be different for different languages.

For FFmpeg, specifying the "desktop" can capture the desktop. 
For the jire version, the desktop parameter is not supported. my version is support

**Comment by xtherk** [comment]
> **Use built-in GDI screengrabber**
You can also use [gdigrab](https://ffmpeg.org/ffmpeg-devices.html#gdigrab) as input device to grab video from the Windows screen.
To capture all your displays as one big contiguous display:
`ffmpeg -f gdigrab -framerate 30 -i desktop output.mkv`

see https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by lihuate** [comment]
@xtherk hi ，I'm doing it,,,scaling 150% win .but,,Broken Way of Working
![image](https://user-images.githubusercontent.com/26449899/196598701-2ca2a3c8-dbbc-4383-ac50-7c6fc1d36f17.png)
我想让他在150%缩放下工作233，，我该怎么做 (‾◡◝)

**Comment by senoxe** [comment]
hi i am past the build step, now im running the Start Overwatch 4.0.0 and in game with magenta set, i am getting this error any idea how to get it to work? 
![ow2](https://user-images.githubusercontent.com/116140685/196600385-99cb6b61-db54-4cb3-bdb9-7f299554f442.png)

**Comment by xtherk** [comment]
> @xtherk hi ，I'm doing it,,,scaling 150% win .but,,Broken Way of Working
> ![image](https://user-images.githubusercontent.com/26449899/196598701-2ca2a3c8-dbbc-4383-ac50-7c6fc1d36f17.png)
> 我想让他在150%缩放下工作233，，我该怎么做 (‾◡◝)

暂时只能更改为100%来让它工作

**Comment by xtherk** [comment]
> hi i am past the build step, now im running the Start Overwatch 4.0.0 and in game with magenta set, i am getting this error any idea how to get it to work? 
> ![ow2](https://user-images.githubusercontent.com/116140685/196600385-99cb6b61-db54-4cb3-bdb9-7f299554f442.png)
> 

This is not error, see what I said above

**Comment by senoxe** [comment]
sorry i am very new to this which step am i lookin to read?

**Comment by yege16888** [comment]
![1666155742(1)](https://user-images.githubusercontent.com/22924516/196601762-d5281bc1-52ac-4e0b-baf0-d2d69cd000d1.jpg)
I use the default configuration and aim at either of these two targets and it will automatically move the center of aim to a position in between the two targets.
Which setting should I adjust to solve this problem

**Comment by senoxe** [comment]
i have the ffmpeg downloaded i just dont know how to use it to get it working still have the same code as abve :(

**Comment by yege16888** [comment]
> 我下载了 ffmpeg 我只是不知道如何使用它来让它工作 仍然有与 abve 相同的代码 :( 我对此很陌生，我看了一个视频来安装 ffmpeg 但我不知道如何让它工作

If you are playing in full screen, change the configuration: window_title_search=desktop


If you are playing a full-screen windowed game, change the configuration: window_title_search=XXX XXX for the title of your game window

The image you posted has no error message and is displayed normally.

**Comment by yege16888** [comment]
> i have the ffmpeg downloaded i just dont know how to use it to get it working still have the same code as abve :( im very new to this, i watched a video to install ffmpeg but im not sure how to get it to work



If you are playing in full screen, change the configuration: window_title_search=desktop


If you are playing a full-screen windowed game, change the configuration: window_title_search=XXX XXX for the title of your game window

The image you posted has no error message and is displayed normally.

**Comment by xtherk** [comment]
@senoxe 
you don't need to download ffmpeg

**Comment by senoxe** [comment]
any chance i can speak to someone in discord or share screen? would truly appreciate it

**Comment by xtherk** [comment]
> ![1666155742(1)](https://user-images.githubusercontent.com/22924516/196601762-d5281bc1-52ac-4e0b-baf0-d2d69cd000d1.jpg)我使用默认配置并瞄准这两个目标中的任何一个，它会自动将瞄准中心移动到两个目标之间的位置。我应该调整哪个设置来解决此问题

Reading will solve your problem https://github.com/Jire/Overwatcheat/issues/94

**Comment by senoxe** [comment]
@xtherk i got it working!! :) i just have an issue where it pulls up after it auto aims to the target the crosshair flys upward! can you help me with that?

**Comment by senoxe** [comment]
@xtherk its due to the hitmarkers actually

**Comment by yege16888** [comment]
> > ![1666155742(1)](https://user-images.githubusercontent.com/22924516/196601762-d5281bc1-52ac-4e0b-baf0-d2d69cd000d1.jpg)我使用默认配置并瞄准这两个目标中的任何一个，它会自动将瞄准中心移动到两个目标之间的位置。我应该调整哪个设置来解决此问题
> 
> Reading will solve your problem #94

Thanks

**Comment by senoxe** [comment]
@xtherk the only problem i have is snap way too strong anyway to fix?

**Comment by xtherk** [comment]
> @xtherk the only problem i have is snap way too strong anyway to fix?

Increase sleep time and sensitivity

**Comment by xtherk** [comment]
I opened this issue, not for you to ask me questions, or for me to solve problems for you.
I have no time or obligation to solve problems for you. 

I find that people always ask their own questions without checking whether the problems mentioned by others are solved, some questions I have answered or solved but still ask the same questions, I am tired.

**Comment by senoxe** [comment]
sorry to bother, thank you for the help! i searched i couldnt find anything related to it in the 118

**Comment by xtherk** [comment]
@senoxe  sorry i didn't mean you

**Comment by xtherk** [comment]
> @xtherk the only problem i have is snap way too strong anyway to fix?

You just need to make adjustments according to the description of each parameter in overwatcheat.cfg.

**Comment by xtherk** [comment]
[overwatcheat.txt](https://github.com/Jire/Overwatcheat/files/9817800/overwatcheat.txt)

Hope it can help you @senoxe

**Comment by senoxe** [comment]
@xtherk oh ok, ya im testing them i just dont know whats the maximum values for example "the base float to use to calculate sleep time multiplier. the higher this is, the more smooth and less sticky the aiming will be" i have mine set to 1000.0 i dont know if the values go that high and maybe thats why i dont see a difference?

**Comment by xtherk** [comment]
Just keep it at 1 ` aim_duration_multiplier_base=1.0`
What needs to be changed is `aim_duration_millis` (unit  millis)

**Comment by xtherk** [comment]
Many parameters are meaningless and confusing

**Comment by senoxe** [comment]
kk i think i messed stuff up switching things around so i redownloaded the original .cfg and feels better now ill slowly adjust from here one by one not multiple ty

**Comment by senoxe** [comment]
just trying to make it look as realistic as possible so no manual bans

**Comment by xtherk** [comment]
> just trying to make it look as realistic as possible so no manual bans

yeah, just need to be a qualified actor

**Comment by xtherk** [comment]
To adjust the parameters, you must first figure out what the parameters you are adjusting are used for. You only need to adjust them one by one, not many at a time. For all the viewers watching this thread

**Comment by senoxe** [comment]
with the settings they start you off you aint foolin anyone XD its super ragey

**Comment by senoxe** [comment]
@xtherk if you want a smaller region for it to snap would you change box_width=256
box_height=256 lower?

**Comment by xtherk** [comment]
> @xtherk if you want a smaller region for it to snap would you change box_width=256 box_height=256 lower?

yep

**Comment by senoxe** [comment]
@xtherk last question also ty for help, what values would you set for maximum smoothness for these values
aim_duration_millis=
aim_duration_multiplier_base=
aim_duration_multiplier_max=

im having trouble adjusting them and seeing any noticeable difference

**Comment by xtherk** [comment]
@senoxe 
You don't need care about these two parameters `aim_duration_multiplier_base` and `aim_duration_multiplier_max`, just need only set to 1.
You only need to set this one parameter. `aim_duration_millis`

I don't really know how to explain these 2 parameters to you, it really doesn't matter to you

**Comment by senoxe** [comment]
thank you for your help! <3

**Comment by Austinw1123** [comment]
AL lib: (EE) ALCwasapiPlayback_open: Device init failed: 0x80070490 

im getting this

**Comment by Spontaneously** [comment]
![image](https://user-images.githubusercontent.com/12773573/196684361-ac216807-2984-4fab-b1a2-1c3907c642c6.png)

I applied the solution you suggested to the situation of being stuck between two targets. I get such an error when I open builder for rebuild. Can you help?

**Comment by hw1992** [comment]
![image](https://user-images.githubusercontent.com/29779220/196686238-81fa3d71-742c-4749-8b20-154668d163f0.png)

**Comment by senoxe** [comment]
@xtherk xtherk, for anyone in the future that is asking for any legit settings i want to provide you with what someone from the overwatcheat discord provided me with. giving credit where credit is due. @Atheno I'lea on discord. these are pretty well made settings to consider for legitimate play so you are not manually banned. Send these to anyone who asks you if you like. They are very solid!


millis = 1.5
multiplier_base=4 (or 3 if you want to a little stronger smooth)
multiplier_max= 1
aim_max_move = 50
jiter = 10
aim_offset_y= 0.75 (for head) or 0.90 (body)
fps= 300 (trully recommend you running at 300 or 200 fps, anything else looks shit)
(for 1920x1080p resolution only)
box_width=64 / box_height=96  if you want to more legit feeling and less fake positives
box_width=128 andbox_height=156 if you just want to hold mouse button and kill without even aim correctly
idk if sensitivity matter when calcs multiplier but im using 10.0 btw

**Comment by xtherk** [comment]
@senoxe thank you very much

**Comment by Lee890917** [comment]
![微信截图_20221020165625](https://user-images.githubusercontent.com/116264576/196905033-fec7c3b3-3ef6-46be-8e1f-89970e664fe0.png)
This problem has been bothering me all day, can anyone help me? Thanks!

**Comment by Spontaneously** [comment]
> ![image](https://user-images.githubusercontent.com/12773573/196684361-ac216807-2984-4fab-b1a2-1c3907c642c6.png)
> 
> I applied the solution you suggested to the situation of being stuck between two targets. I get such an error when I open builder for rebuild. Can you help?
> 
> and;
> 
> After killing a lone target with a spray, the cross instantly slides up. What could be the reason for this?

Can u help me? @xtherk

**Comment by xtherk** [comment]
> > ![image](https://user-images.githubusercontent.com/12773573/196684361-ac216807-2984-4fab-b1a2-1c3907c642c6.png)
> > I applied the solution you suggested to the situation of being stuck between two targets. I get such an error when I open builder for rebuild. Can you help?
> > and;
> > After killing a lone target with a spray, the cross instantly slides up. What could be the reason for this?
> 
> Can u help me? @xtherk

Please post a screenshot of your modified code

**Comment by xtherk** [comment]
@Lee890917 Please modify `window_title_search=desktop`, and modify the game to full screen, then try again

**Comment by Spontaneously** [comment]
> > > ![image](https://user-images.githubusercontent.com/12773573/196684361-ac216807-2984-4fab-b1a2-1c3907c642c6.png)
> > > I applied the solution you suggested to the situation of being stuck between two targets. I get such an error when I open builder for rebuild. Can you help?
> > > and;
> > > After killing a lone target with a spray, the cross instantly slides up. What could be the reason for this?
> > 
> > 
> > Can u help me? @xtherk
> 
> Please post a screenshot of your modified code

![image](https://user-images.githubusercontent.com/12773573/196924862-cb944959-9f0f-4a03-bc22-5cbb9b9a8f3e.png)

I applied the change in AimFrameHandler to try the solution in post 94 and when I tried to open "build" again I got the attached error. My settings in the main file were just changed with what @senoxe suggested. @xtherk

**Comment by xtherk** [comment]
> > > > ![image](https://user-images.githubusercontent.com/12773573/196684361-ac216807-2984-4fab-b1a2-1c3907c642c6.png)
> > > > I applied the solution you suggested to the situation of being stuck between two targets. I get such an error when I open builder for rebuild. Can you help?
> > > > and;
> > > > After killing a lone target with a spray, the cross instantly slides up. What could be the reason for this?
> > > 
> > > 
> > > Can u help me? @xtherk
> > 
> > Please post a screenshot of your modified code
> 
> ![image](https://user-images.githubusercontent.com/12773573/196924862-cb944959-9f0f-4a03-bc22-5cbb9b9a8f3e.png)
> 
> I applied the change in AimFrameHandler to try the solution in post 94 and when I tried to open "build" again I got the attached error. My settings in the main file were just changed with what @senoxe suggested. @xtherk 
> 

![IMG_20221020_185102.jpg](https://user-images.githubusercontent.com/33031194/196929462-ec501de6-c2c0-4bf1-9487-38a848f91f87.jpg)

You did not replace it as I said, please add it according to the annotations in the picture

**Comment by Spontaneously** [comment]
> 

![image](https://user-images.githubusercontent.com/12773573/196931223-56b76b6e-72b4-4617-9720-b0798baa7b3b.png)

This is how I edited it and opened Build from the beginning. This time, the number of errors decreased to 1.
@xtherk 

![image](https://user-images.githubusercontent.com/12773573/196931872-3b4508d3-a4aa-46f7-92b2-75c227214c57.png)

**Comment by Spontaneously** [comment]
> 

I did a rebuild, but this time the cross moves unrelated to the target. Goes far to the left of the target instead.

**Comment by xtherk** [comment]
> > 
> 
> I did a rebuild, but this time the cross moves unrelated to the target. Goes far to the left of the target instead. I'm using a 2K monitor. I will be glad if you answer accordingly :(
>  @xtherk 

Oh, you made a mistake, please restore the file and follow this link to modify it again

https://github.com/Jire/Overwatcheat/issues/94

**Comment by xtherk** [comment]
@Spontaneously Restore to the original file, please modify it carefully

**Comment by xtherk** [comment]
@Spontaneously ![196615400-d12bf88f-5581-4f45-9ec1-7a48be10eecd.png](https://user-images.githubusercontent.com/33031194/196939557-ac59eb68-cebd-4329-a665-431ab14190e4.png)

Modify according to this picture. 

Please don't use my time to pay for your carelessness !!!

**Comment by Spontaneously** [comment]
> 

Calm down. I understand why Cross was acting irrelevant. HeadShot hits the target, Magenta, body hits White effect. If we shoot and kill both HeadShot, we get a skull and effect in Magenta color. This causes Cross to continue following for a while. Release your tension in another way, my friend. You're the one who said in the beginning that he would help. I only asked 3 questions.

**Comment by xtherk** [comment]
> Calm down. I understand why Cross was acting irrelevant. HeadShot hits the target, Magenta, body hits White effect. If we shoot and kill both HeadShot, we get a skull and effect in Magenta color. This causes Cross to continue following for a while. Release your tension in another way, my friend. You're the one who said in the beginning that he would help. I only asked 3 questions.

I'm so sorry, maybe I'm closing this thread, I'm just posting this thread to make it work for those who have aimbot not working, and I've answered most of the questions that come up, see one or two posts for details.
And I was detailed enough about how to replace in https://github.com/Jire/Overwatcheat/issues/94 , this problem can be avoided if you can be careful, I'm really going to crash if everyone does this, I'm really sorry

**Comment by lihuate** [comment]
@xtherk  That’s so kind of you！You’re the best.     I wish you all the happiness in the world (‾◡◝)

**Comment by Lee890917** [comment]
> @Lee890917请修改 ，并将游戏修改为全屏，然后重试`window_title_search=desktop`

Thanks!

**Comment by aocun** [comment]
bro do u know where to download the interception driver? I found it on the youtube channel of jire, but couldnt install it

**Comment by Adam24866** [comment]
> 

how did you fix that,i have done what ever i can do. It seems there is no error, but didn't work for me

**Comment by Adam24866** [comment]
> 嗨，我已经完成了构建步骤，现在我正在运行 Start Overwatch 4.0.0 并且在使用洋红色设置的游戏中，我收到这个错误知道如何让它工作吗？ ![ow2](https://user-images.githubusercontent.com/116140685/196600385-99cb6b61-db54-4cb3-bdb9-7f299554f442.png)

how did you fix that,i have done what ever i can do. It seems there is no error, but didn't work for me

**Comment by aocun** [comment]
1.Change your capture window to desktop 2.Change your display zoom to
100%

**Comment by aocun** [comment]
3.Make sure you run cmd in administrator mode, install the interception driver and restart your pc

**Comment by aocun** [comment]
Drive download link:    https://github.com/oblitum/interception/releases/tag/v1.0.1

**Comment by Adam24866** [comment]
> 1.将您的捕获窗口更改为桌面 2.将您的显示缩放更改为 100%

great work for me thx！but it still over aim to left side
