### ISSUE TITLE
Will v3.5.0 work with OW2?

### ISSUE THREAD

**Issue by ageofmyth** [Jire/Overwatcheat#186]
Hi there,

I wanted to make thread for people to check regarding the previous version of OWC - v3.5.0.

Is upgrading to 4.0.0 necessary to have the aimbot work for OW2 and be undetectable?  I built v3.5.0 successfully and configured it properly after many hours of troubleshooting, so I'd prefer to avoid rebuilding it if possible :)

**Comment by xtherk** [comment]
No need to upgrade to 4.0.0

4.0.0 just upgraded dependency versions and build scripts

**Comment by ageofmyth** [comment]
Great to hear! I'll try it out then.
