### ISSUE TITLE
No error but it dont work :(

### ISSUE THREAD

**Issue by Flowing8175** [Jire/Overwatcheat#220]
```
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/C:/Users/hsome/Downloads/Overwatcheat-5.1.0/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Info: [gdigrab @ 0000022f002d9980] Found window 전체화면 프로젝터 (미리보기), capturing 256x256x32 at (1592,592)

Info: Input #0, gdigrab, from 'title=전체화면 프로젝터 (미리보기)':

Info:   Duration:
Info: N/A
Info: , start:
Info: 1674057544.716831
Info: , bitrate:
Info: 188782 kb/s
Info:

Info:   Stream #0:0
Info: : Video: bmp, bgra, 256x256, 188782 kb/s
Info: ,
Info: 90 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:


```

my cmd window
nothing seems to be wrong
but nothing's happening at my aim
wth is wrong

**Comment by lilmagic45** [comment]
make sure interception is downloaded correctly and try playing around with different resolutions

**Comment by Flowing8175** [comment]
already tried different resolutions and reinstalled interception driver 99999 times bro...

**Comment by lilmagic45** [comment]
is your scale and layout set to 100% in your display setting?

**Comment by Flowing8175** [comment]
> is your scale and layout set to 100% in your display setting?
yea I use 100%

**Comment by Flowing8175** [comment]
https://github.com/Jire/Overwatcheat/issues/207#issuecomment-1356641431

same as mine

**Comment by lilmagic45** [comment]
that's odd. I'm not too sure what else could be the issue. only thing i can think of is did you move the interception dll to your overwatch 5.1.0 folder?

**Comment by Flowing8175** [comment]
> that's odd. I'm not too sure what else could be the issue. only thing i can think of is did you move the interception dll to your overwatch 5.1.0 folder?

ofc I did.. I should just re-install everything in owcheat and interception driver.

**Comment by Flowing8175** [comment]
I just reinstalled interception driver and the config file, and I got another error msg which tells me the interception isn't installed. I'll continue this thread in new issue since it appeared new error msg.

**Comment by Flowing8175** [comment]
wait bro, i put the x64 dll not x86 into the folder and ITS WORKINGGGGGGGGGGGGGG YESSSSSSSSSSSS
