### ISSUE TITLE
Doesn't work anymore after season 3 update

### ISSUE THREAD

**Issue by Kukupie123** [Jire/Overwatcheat#227]
[main] INFO net.openhft.chronicle.core.Jvm - Chronicle core loaded from file:/F:/Overwatcheat-main/build/Overwatcheat%205.1.0/Overwatcheat%205.1.0.jar
Info: [gdigrab @ 000001f48a89e540] Capturing whole desktop as 64x32x32 at (928,524)

[Aim Bot] INFO net.openhft.affinity.AffinityLock - Assigning cpu 2 to Thread[#42,Aim Bot,9,main] on thread id 13660
[Aim Bot] WARN net.openhft.affinity.impl.WindowsJNAAffinity - Tried to set affinity to {2} but was {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} you may have in sufficient access rights
Info: Input #0, gdigrab, from 'desktop':

Info:   Duration:
Info: N/A
Info: , start:
Info: 1675862957.319100
Info: , bitrate:
Info: 3958 kb/s
Info:

Info:   Stream #0:0
Info: : Video: bmp, bgra, 64x32, 3958 kb/s
Info: ,
Info: 60 fps,
Info: 1000k tbr,
Info: 1000k tbn
Info:

**Comment by xDreamscape** [comment]
Yep same for me, they terminated it

**Comment by Jire** [comment]
I can confirm that it still works. You may have gotten frame capture banned for using other cheats, and need to switch to capturing via OBS.

**Comment by kuchuk-borom-debbarma** [comment]
Correct it still works
Switched to desktop capture

**Comment by Baconartist** [comment]
> I can confirm that it still works. You may have gotten frame capture banned for using other cheats, and need to switch to capturing via OBS.

It isn't working for me. I do think I got frame capture banned, but I successfully used OBS to track the game. No errors, but it still doesn't work. It is set to windowed fullscreen, enemies are magenta, I just can't figure out the issue. Got discord?
