### ISSUE TITLE
Using the button that is bound to "aim_key" presses also Z and Alt

### ISSUE THREAD

**Issue by Thepaladin29** [Jire/Overwatcheat#228]
Idk how to explain it better tbh. When I press the button it also presses the buttons mentioned above

**Comment by Jire** [comment]
This is intentional, to disable the in-game overlay when you are firing, so that the name overlay doesn't interfere with character border detection.

To disable this feature, in _overwatcheat.cfg_ you can set the _toggle_in_game_ui_ to _false_ like `toggle_in_game_ui=false`
