### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by JackyOreo** [Jire/Overwatcheat#28]
Hi,

First of all thanks for all the work you put in this project and it's awesome that you gave us the source code, that way noobs like me can learn a thing or to instead of just blindely using someone else's work. 
I have a question that I can't figure out myself unfortunetely, I want to change the code so it's more unique and has another signature. That way I hope that when the public one is detected I can still use mine since it's altered. One problem though, I don't have the slightest idea how to even begin with this. So I hoped that maybe you could give me something to start with, since you probably did this for yourself to so you could keep on using the cheat without worries. 
Thanks in advance.

Kind regards,
Jacky

**Comment by ChianDev** [comment]
This is java so you are prob screwed as its very hard to hide signatures with it
java based cheat providers often have to ditch their source code once they are detected

**Comment by JackyOreo** [comment]
Ooh oke thanks for the reply. I guess I won't be using it anymore than since it's kinda popular these days and will be detected very quickly.
