### ISSUE TITLE
It says gradlew is not rcognized as......... ( U can Close)

### ISSUE THREAD

**Issue by khtur** [Jire/Overwatcheat#32]

**Comment by khtur** [comment]
'gradlew' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by EmailedTheBear** [comment]
It is currently down, you might have to wait.

**Comment by EmailedTheBear** [comment]
That happened to me when I first installed it, I'm guessing you just did which makes me think it is the same problem as mine. I just kept trying, you might have to be Border less window mode if that is your error.

**Comment by khtur** [comment]
I fixed it by copying the files and pasting it in the previous folder
