### ISSUE TITLE
Not really an issue but..

### ISSUE THREAD

**Issue by Lonerw0lf** [Jire/Overwatcheat#39]
So, I'm rewriting an universal pixel aimbot using both Overwatcheat and Charlatano as base (logic between them and settings), I wanted to ask you if you know how to convert RGB to HSV or something like checking the shades, I could rewrite the entire program to use HSV only. Here are the reasons:
https://sourceforge.net/p/flowdesigner/wiki/OpenCV/attachment/FindRedColorRGB.jpg with RGB
https://sourceforge.net/p/flowdesigner/wiki/OpenCV/attachment/FindRedColorHSV.jpg with HSV
Of course I'm not planning to use the entire red shade, I'll get a way to get the enemy red outline's original color by checking how much the transparency is worth and make a small range using it, that would make a non HP BAR Aimbot.

Or anything that could use these values:
```Kotlin
RATE_RED_MIN = 55
RATE_RED_MAX = 70
RATE_GREEN_MAX = (100 - RATE_RED_MIN) / 2).toInt()
RATE_BLUE_MAX = RATE_GREEN_MAX
```
Not RGB but  rate/percentage of each color.

**Comment by Lonerw0lf** [comment]
Got it, using:
```Kotlin
var r_p = (((rgb and 0xFF0000) shr 16)*100)/255
var g_p = (((rgb and 0xFF00) shr 8)*100)/255
var b_p = ((rgb and 0xFF)*100)/255
```

**Comment by liangtb** [comment]
@Lonerw0lf Could I test your modified script? Thanks!
