### ISSUE TITLE
Don't download this script, even though implement it, it doesn't properly or correctly work. Don't expect it

### ISSUE THREAD

**Issue by liangtb** [Jire/Overwatcheat#44]
see issue #43

**Comment by liangtb** [comment]
@Jire If it doesn't work right now and you wouldn't fix it, you should unload it and not deceive people.

**Comment by Jire** [comment]
It does work, you just need to research into former issues to find out how to use it.

**Comment by liangtb** [comment]
@Jire I didn't find some solutions about aim to right, I completely implemented this script by obs and windows titles, so the implement is okay, but the problem of this script is found by somebody, nobody solved this problem, Can you want me to find what but nothing?

**Comment by liangtb** [comment]
It's the same as EmailedTheBear's problem, nobody solved this before, what can I find?

**Comment by liangtb** [comment]
@Jire It did work, but not properly work or correctly work!!!!!!!

**Comment by liangtb** [comment]
@Jire Can you explain this? This script maybe good before, but at current it's broken, and you still post here...

**Comment by liangtb** [comment]
@Jire at issue #37 you said it failed, then now you said it does work, how?
I successfully implemented it, but it aimed to right randomly, how it work?

**Comment by liangtb** [comment]
@Jire either you **delete** this script or **update** script, because even though successfully implemented it by obs or other softwares, **_it doesn't work in any way._**

**Comment by Jire** [comment]
The easiest way to resolve the center is by processing through red pixels; counting the number of consecutive horizontal pixels within the color range, and then using the center pixel, which is the first horizontal pixel plus half the total spanning red pixels.

**Comment by liangtb** [comment]
@Jire Can you send me a modified script or single document? Thanks! I will delete these issues! Sorry!
ltingbiao@hotmail.com

**Comment by liangtb** [comment]
@Jire  as you said in #37, the red pixels can not be detected by current way.

**Comment by Jire** [comment]
I've shared a simple and effective solution to the problem --- It's up to you to implement the solution, or wait until I get around to it.

**Comment by liangtb** [comment]
The easiest way is an impossible way which blocked by blizzard.

**Comment by liangtb** [comment]
I've no ideas about java or kotlin.... I understand your meaning but not able to modify it unless it's based on python or C.

**Comment by Jire** [comment]
Blizzard's "block" is to generate random shades of red. These shades of red still form an obvious pattern, and fall within a color range. With the solution I provided, you can extract the center of the HP bar, and thus have a flawless cheat. 😉

**Comment by liangtb** [comment]
Can you give me a temporary solution and I can test it by my chance?

**Comment by liangtb** [comment]
@Jire  I can feedback some info for you.

**Comment by liangtb** [comment]
Overwatcheat/src/main/kotlin/com/overwatcheat/aimbot/AimBot.kt
This file should be modified by your meaning, am I right?

**Comment by liangtb** [comment]
IF you don't have time to test it, I can test it and feedback for you...Thanks!😊

**Comment by EmailedTheBear** [comment]
How would you modify it?

**Comment by liangtb** [comment]
you should ask @Jire , he provided an idea before, you look up and will find it.

**Comment by EmailedTheBear** [comment]
I'm not quite sure how to do it.

**Comment by liangtb** [comment]
#jire Count the number of consecutive horizontal pixels within the color range, then use the center pixel, which is the first horizontal pixel plus half the total spanning red pixels.

**Comment by EmailedTheBear** [comment]
Okay, how do you find the number. Quite sorry, I'm very nieve

**Comment by liangtb** [comment]
@Jire can you make a temporary method? I and em will test it on our won and feedback for you.

**Comment by liangtb** [comment]
@Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire @Jire

**Comment by EmailedTheBear** [comment]
Please don't spam him.

**Comment by liangtb** [comment]
@EmailedTheBear you wasted several days to implement this script then you found it doesn't work because of the aim issue.

**Comment by EmailedTheBear** [comment]
Patience.

**Comment by EmailedTheBear** [comment]
Several months.

**Comment by liangtb** [comment]
I implemented in several hours then found it didn't work......can't imagine people wasted several days or months then found it's nothing useful....

**Comment by listenmotherfucker** [comment]
@liangtb Listen you fucking cocksucking chink get the fuck outta here demanding shit for free. I know for a fact jire could not give less of a shit what the fuck you think or say you worthless begging cunt

**Comment by liangtb** [comment]
@listenmotherfucker you can say anything ugly but the fact is here it doesn't work at current time, you can't change it. 
Say anything, nigger!
