### ISSUE TITLE
[Error] Capture area.

### ISSUE THREAD

**Issue by Apocryphoon** [Jire/Overwatcheat#72]
Hello Goodnight!

Sorry my English, I'm not an American. I am a Brazilian junior developer, I am trying to run your application all right so far, except that with the game open, when trying to run 'Start Overwatcheat 3.1.0' it returns me the following.

My monitor is an ultrawide (2560 x 1080), in the game I am using full screen, is there anything I can do?

![image](https://user-images.githubusercontent.com/32386767/112576649-78d77700-8dd1-11eb-8ca7-b6ee8f8a327e.png)

**Comment by gedissxd** [comment]
use borderless

**Comment by JohnSilver2077** [comment]
useless borderless,it can't find right window

**Comment by Apocryphoon** [comment]
Hello, follow print in Portuguese, I couldn't put it in English but it is already in "full screen without border" mode.

"useless borderless,it can't find right window", Sorry I did not understand

![image](https://user-images.githubusercontent.com/32386767/112674362-97c32100-8e44-11eb-96d0-457ef022d649.png)

**Comment by Apocryphoon** [comment]
I realized that he cannot find the title of the application 'title = [error]', I tried it in full screen mode, and full screen without border, both give the same error

**Comment by JohnSilver2077** [comment]
The game has used borderless full screen, but there is no self aiming effect,In this case, you can use the administrator to run bat




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月27日(星期六) 凌晨2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jire/Overwatcheat] [Error] Capture area. (#72)





 
Hello, follow print in Portuguese, I couldn't put it in English but it is already in "full screen without border" mode.
 
"useless borderless,it can't find right window", Sorry I did not understand

**Comment by Apocryphoon** [comment]
Hm, ok

I ran the .bat as an administrator and used the overwatch in full screen mode with no borders, the msg changed but, it still doesn't work

![image](https://user-images.githubusercontent.com/32386767/112675507-00f76400-8e46-11eb-883b-424f66ed60f6.png)

**Comment by JohnSilver2077** [comment]
Sí, no tengo ningún efecto aquí tampoco, así que no sé cómo solucionarlo



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月27日(星期六) 凌晨2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jire/Overwatcheat] [Error] Capture area. (#72)





 
Hm, ok
 
I ran the .bat as an administrator and used the overwatch in full screen mode with no borders, the msg changed but, it still doesn't work

**Comment by JohnSilver2077** [comment]
Soy chino y estoy muy feliz de poder ayudarte


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jire/Overwatcheat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月27日(星期六) 凌晨2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jire/Overwatcheat] [Error] Capture area. (#72)





 
Hm, ok
 
I ran the .bat as an administrator and used the overwatch in full screen mode with no borders, the msg changed but, it still doesn't work

**Comment by Apocryphoon** [comment]
wowww, eres chino?

**Comment by Apocryphoon** [comment]
Tengo que trabajar, pero como OBS
