### ISSUE TITLE
Failure: Build failed with an exception

### ISSUE THREAD

**Issue by Formeis** [Jire/Overwatcheat#84]
![Screenshot 2021-04-13 223543](https://user-images.githubusercontent.com/82468716/114603329-a6189600-9ca8-11eb-932d-f235ba22f6f7.png)

**Comment by Formeis** [comment]
I have tried many things but i cannot do anything about it

**Comment by JackMeds** [comment]
![image](https://user-images.githubusercontent.com/38741783/114639776-3aaee280-9d01-11eb-8989-b1adb2ed3e73.png)

**Comment by Formeis** [comment]
I tried making it run on jdk. even removed jre for sometime off the comp. still didn't help
i then went into environment variables to set the path but to no avail.

**Comment by Formeis** [comment]
i couldn't even download the newest version of gradle on my pc. it said the same thing there. then i found a github issue page somewhere and downloaded gradle from there and it installed somehow

**Comment by Formeis** [comment]
Well it has been fixed. it seemed that when i used AdoptOpenJDK which Jire said to download it didn't work. i downloaded the normal jkd from the oracle website and it worked now :DD
